# Generated by Django 5.1.6 on 2025-04-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='texts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
